name: "Tests"

on:
  push:
    paths:
      - "lib/**"
      - "test/**"
      - ".github/workflows/tests.yml"
      - "package.json"
      - "Gruntfile.js"
  pull_request:
    paths:
      - "lib/**"
      - "test/**"
      - ".github/workflows/tests.yml"
      - "package.json"
      - "Gruntfile.js"

jobs:

  build:

    name: "Run tests"
    runs-on: ubuntu-latest

    steps:

      - name: "Checkout the repository"
        uses: actions/checkout@v3

      - name: "Set up Node 18"
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: "Install Node dependencies"
        run: |
          npm install

      - name: "Run lint"
        run: |
          npm run lint

      - name: "Run tests"
        run: |
          npm run test
